export type TaskStatus = string;

export type SortConfig = {
  key: keyof Task | 'wbs';
  direction: 'asc' | 'desc';
} | null;

/** 프로젝트별 투입인원·투입비율. 작업의 기간/공수 계산에 사용 */
export interface ProjectAssignment {
  assignee: string;
  /** 기본 투입비율(%). 월별 미설정 시 전체 기간에 적용 */
  allocationPercent: number;
  /** 기간별 월별 투입비율. 키: "YYYY-MM", 값: 해당 월 투입비율(%). 있으면 해당 월에는 이 값 사용 */
  monthlyAllocations?: Record<string, number>;
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  startDate?: string; // ISO string (YYYY-MM-DD)
  endDate?: string; // ISO string (YYYY-MM-DD). WBS 작업은 이 기간 범위를 벗어날 수 없음
  /** 프로젝트별 투입인원·투입비율. 이 프로젝트 소속 작업의 기간·공수 계산에 적용 */
  assignments?: ProjectAssignment[];
  /** 프로젝트 소유자 (Supabase auth.users id) */
  ownerId?: string;
  /** 작업 최소 공수 기준(일). 0.5, 1, 3 등. WBS 작업 세부 분류에 사용 */
  minWorkEffortDays?: number;
  /** 주간보고용 분류(예: 국책, 매출 등) */
  reportCategory?: string;
  /** 주간보고용 주관기관(예: KRISO, LS전선 등) */
  reportAgency?: string;
  /** 주간보고용 금년도 정부출연금 또는 예산 정보 */
  reportBudgetThisYear?: string;
  /** 주간보고용 전체 기간 표시(예: '26년 9월', '23.04 ~ 26.12') */
  reportTotalPeriod?: string;
  /** 주간보고용 과제명 약어(예: AI스마트팩토리 연구) */
  reportNameShort?: string;
  /** 주간보고용 전체과제명(예: 고하중 장조장 해저 케이블 생산을 위한 디지털 트윈 AI 팩토리 기술 개발) */
  reportNameFull?: string;
  /** 앱 초기화 시 자동 생성된 임시 프로젝트 여부. auto-prune 대상 */
  _autoGenerated?: boolean;
  /** 사용자 정의 그룹 ID. wbsSettings.projectGroups의 항목과 매핑된다. */
  groupId?: string;
}

export interface Task {
  id: string;
  projectId: string;
  parentId: string | null;
  name: string;
  startDate: string; // ISO string
  endDate: string; // ISO string
  progress: number; // 0-100
  assignee: string;
  status: TaskStatus;
  expanded?: boolean; // UI state for tree view
  dependencies?: string[]; // Array of predecessor task IDs
  workEffort?: number; // Man-days (작업 공수)
  /** 진척 가중치. 지정 시 상위 작업·요약 진척률에 이 값을 우선 사용 (없으면 공수 기준) */
  weight?: number;
  description?: string;
  checklist?: { id: string; text: string; completed: boolean }[];
  deliverables?: string;
  /** 서버 갱신 시각(ISO). 동시 수정 감지(낙관적 잠금)용 */
  updatedAt?: string;
  /** 마일스톤 여부. true면 일정 상 하나의 시점(이정표)으로 표시 */
  isMilestone?: boolean;
  /** 이슈 여부. true면 이슈 작업으로 강조 표시 */
  isIssue?: boolean;
  /** 베이스라인 시작일. 설정 시 해당 작업의 기준 일정으로 사용 */
  baselineStartDate?: string;
  /** 베이스라인 종료일 */
  baselineEndDate?: string;
  /** 베이스라인 공수(일) */
  baselineWorkEffort?: number;
  /** 사용자가 수동 수정한 항목. AI 업데이트 시 이 필드들은 덮어쓰지 않음. progress 잠금 시 상위 작업 진척률은 하위 롤업으로 덮어쓰지 않음 */
  userLockedFields?: ('dependencies' | 'startDate' | 'endDate' | 'workEffort' | 'progress')[];
}

export interface FilterState {
  /** 'all' = 모든 프로젝트, 배열 = 선택한 프로젝트들의 작업만 표시 */
  projectIds: 'all' | string[];
  status: TaskStatus | 'all';
  assignee: string;
  /** true면 담당자 미배정 작업만 표시 */
  assigneeUnassignedOnly?: boolean;
  startDate: string;
  endDate: string;
  /** true면 마일스톤 작업만 표시 */
  milestoneOnly?: boolean;
  /** true면 이슈 작업만 표시 */
  issueOnly?: boolean;
  /** 레벨 필터: 숫자면 해당 WBS 레벨만 표시, 'all'이면 전체 */
  level?: number | 'all';
  /** true면 완료 기한이 지났는데 아직 미완료인 작업만 표시 */
  pastDueOnly?: boolean;
  /** true면 이번 주에 완료(상태 'done' + 종료일이 이번 주)된 작업만 표시 */
  completedThisWeekOnly?: boolean;
  /** 작업명/설명 텍스트 검색 */
  searchText?: string;
}
